dynamic: install


all: install


install:
	cp -f libwlbcmcrypto.so_$(PROFILE)_save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_$(PROFILE)_save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f libwlupnp.so_$(PROFILE)_save $(INSTALL_DIR)/lib/libwlupnp.so
	cp -f eapd_$(PROFILE)_save $(INSTALL_DIR)/bin/eapd
	cp -f lld2d_$(PROFILE)_save $(INSTALL_DIR)/bin/lld2d
	cp -f wrt54g.large.ico_$(PROFILE)_save $(INSTALL_DIR)/etc/wrt54g.large.ico
	cp -f wrt54g.small.ico_$(PROFILE)_save $(INSTALL_DIR)/etc/wrt54g.small.ico
	cp -f nas_$(PROFILE)_save $(INSTALL_DIR)/bin/nas
	cp -f nvram_$(PROFILE)_save $(INSTALL_DIR)/bin/nvram
	cp -f libnvram.so_$(PROFILE)_save $(INSTALL_DIR)/lib/libnvram.so
	cp -f nvram_params_$(PROFILE)_save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f nvramUpdate_$(PROFILE)_save $(INSTALL_DIR)/bin/nvramUpdate
	cp -f wlctl_$(PROFILE)_save $(INSTALL_DIR)/bin/wlctl
	cp -f libwlctl.so_$(PROFILE)_save $(INSTALL_DIR)/lib/libwlctl.so
	cp -f wlmngr_$(PROFILE)_save $(INSTALL_DIR)/bin/wlmngr
	cp -f wlevt_$(PROFILE)_save $(INSTALL_DIR)/bin/wlevt
	cp -f libwlmngr.so_$(PROFILE)_save $(INSTALL_DIR)/lib/libwlmngr.so
	cp -f wps_monitor_$(PROFILE)_save $(INSTALL_DIR)/bin/wps_monitor
	cp -f libwps.so_$(PROFILE)_save $(INSTALL_DIR)/lib/libwps.so
