dynamic: install


all: install


install:
	cp -f libwlbcmcrypto.so_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f libwlupnp.so_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/lib/libwlupnp.so
	cp -f eapd_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/eapd
	cp -f lld2d_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/lld2d
	cp -f wrt54g.large.ico_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/etc/wrt54g.large.ico
	cp -f wrt54g.small.ico_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/etc/wrt54g.small.ico
	cp -f nas_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/nas
	cp -f nvram_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/nvram
	cp -f libnvram.so_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/lib/libnvram.so
	cp -f nvram_params_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f nvramUpdate_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/nvramUpdate
	cp -f wlctl_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/wlctl
	cp -f libwlctl.so_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/lib/libwlctl.so
	cp -f wlmngr_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/wlmngr
	cp -f wlevt_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/wlevt
	cp -f libwlmngr.so_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/lib/libwlmngr.so
	cp -f wps_monitor_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/bin/wps_monitor
	cp -f libwps.so_VR-3032u-IPv4_JAZ_save $(INSTALL_DIR)/lib/libwps.so
